name: Fetch Plugin & Commit
on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: Plugin release tag.
        required: false
        default: 'next'
env:
  GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}
jobs:
  Fetch-Plugin-And-Commit:
    name: Fetch Plugin & Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies
      - name: Fetch Plugin
        run: npm run fetch-plugin -- '${{ github.event.inputs.release-tag }}'
        shell: bash
      - name: Commit & Push
        run: |
          git config --global user.name 'AgogBot'
          git config --global user.email 'agogbot@users.noreply.github.com'
          git add assets
          git commit -m "[skip ci] Fetch plugin with release tag '${{ github.event.inputs.release-tag }}'."
          git push
